version: '3.8'
services:
  mssql-server:
    build:
      context: .
      dockerfile: mssql2.dockerfile
    
    # ports:
    # - 1433:1433
    networks:
      - my-network

  web-server:
    build:
      context: .
      dockerfile: webserver2.dockerfile
    ports:
      - "5050:80"
    depends_on:
      - mssql-server
    networks:
      - my-network
      
networks:
  my-network:
